### ISSUE TITLE
Issues creating the "wifi_secrets.py" module and getting the RTC to sync with the NTP server.

### ISSUE THREAD

**Issue by tictocdoc** [erikjber/Fish-Feeder-Raspberry-Pico-W#1]
I am having some issues with the code.  It may be because I'm a noob at micropython. I followed the example provided to create the "wifi_secrets.py" file.  I tried several iterations but never could get it to import correctly.  I finally added my SSID and PW directly to the 2 places in "main.py" that call it.  It successfully connected then but now I have a couple of new issues.  I'm getting the follow error when I run "main.py".
![ex5JKyBBf2T6Bb59](https://user-images.githubusercontent.com/10298807/203488752-0b34acd1-030e-476b-b3a6-9f3f3ef605a3.png)

The RTC does not seem to be able to sync. I manually set the date/time via a different RTC script successfully so I think the i2c device address is correct (left it at the default). So since the RTC isn't able to sync I can't get any scheduled feeding to trigger.  The "manual" button on the app works so I know it is connected to wifi.  I swapped out the RTC module, set it as before and now it seems to be incrementing however it still can't sync.

I appreciate any help or suggestions you could give me.
Thanks,
Michael

**Comment by erikjber** [comment]
The error indicates that the Network Time Protocol (NTP) sync failed, not the RTC time.  

The time sync is in two parts:
First the NTP time sync downloads the correct time from an NTP server. 
Then that time is sent to the RTC module.  

It is the first step that fails.  Your RTC module appears to be working correctly, as indicated by the line starting with "RTC datetime after sync".

 
There are many possible reasons the NTP time sync failed. The first that come to mind are:  
1. NTP server is temporarily down or overloaded.  
2. Slow network connection.  
3. NTP protocol is blocked by your ISP or your router.  


By default the Micropython ntptime package uses the time server at ntp.ntsc.ac.cn. You can choose another time server by editing line  56 of tools.py, for example like this:   
`ntptime.settime(server = 'time1.google.com')`   
If you find an NTP server that works it is likely that reason 1 was the cause.


Note that the feeder will work even if the NTP time sync fails, it will just not have any idea what the real time is unless you have manually programmed the correct time into the RTC module.

**Comment by erikjber** [comment]
Keep also in mind that the system expects the RTC to run on UTC. So if you manually program the RTC to your local time but you live in a timezone that is offset 8 hours from UTC, all your feeding times will be 8 hours late.

**Comment by erikjber** [comment]
There is a list of public NTP servers here:
https://gist.github.com/mutin-sa/eea1c396b1e610a2da1e5550d94b0453

**Comment by tictocdoc** [comment]
Ok, that makes sense.  I noticed when I used the 1st RTC module, while it was able to sync successfully, the time shown was 6 hours off.  I live in America / Chicago - (UTC -6).  I thought the sync would check the system time on my pc to determine which time zone I'm in and whether daylight savings time was in effect.  How would I indicate the UTC time offset?
 I tried setting schedules taking into account the time difference but they still never triggered.   I also noticed that the "hot spot" that the pico creates shows up as "dd-wrt".  When my phone scans for available networks.  I don't run dd-wrt on my routers only stock firmware.  Does this seem right to you?  Also, I would like to use the "wifi_secrets.py" module if I can get it to work.  I have searched for examples of how this file should be formatted but haven't been able to find one that worked.

**Comment by erikjber** [comment]
Timezones and daylight savings can trick one up in unexpected ways. That is why the RTC module in the feeder must be set to UTC.  To figure out the current time in UTC, just look here:   
https://www.timeanddate.com/worldclock/timezone/utc   
   

The app converts from local time to UTC before sending the feeding time to the feeder. If you are in timezone UTC-6, that means adding 6 hours to the local time. If your RTC module is set to local time and your local time is UTC-6, the feeding times will be 6 hours later than scheduled.

The feeder does not create a hotspot. If a network scan shows up a 'dd-wrt' network that is from some other device, could it be your neighbour's router?  

 For information about how to format the wifi_secrets.py file, look here:  
 https://github.com/erikjber/Fish-Feeder-Raspberry-Pico-W/wiki/FAQ

**Comment by tictocdoc** [comment]
Thanks for all of your help!  After removing an expansion router from my network (which I believe was not allowing the Pico to connect properly and hence not allowing the RTC to sync) ,copying a fresh copy of all of the files to the Pico, specifying a local NTP server, and creating the wifi_secrets.py file from your example,  it all now works as desired.  Thanks again for providing such a great project to the fishkeeping community.
